-- Create the trees table
CREATE TABLE IF NOT EXISTS public.trees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_name TEXT NOT NULL DEFAULT 'ต้นไม้ทั่วไป',
    circumference FLOAT8 NOT NULL,
    height FLOAT8 NOT NULL,
    latitude FLOAT8,
    longitude FLOAT8,
    carbon_storage FLOAT8 NOT NULL,
    carbon_value FLOAT8 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.trees ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read the data
CREATE POLICY "Allow public read access"
ON public.trees
FOR SELECT
TO public
USING (true);

-- Create a policy that allows anyone to insert data (for development)
-- In production, you might want to restrict this
CREATE POLICY "Allow public insert access"
ON public.trees
FOR INSERT
TO public
WITH CHECK (true);
